### ISSUE TITLE
404 error for HPO and Variant is wrong

### ISSUE THREAD

**Issue by YuanTian1991** [phenopolis/phenopolis_browser#175] opened 2020-09-01 22:04 UTC
Based on my test, the 401 code is fine for all 4 items (gene/hpo/individual/variant). But the 404 code is wrong for HPO and Variant, see below:

404 means a user has logged in (no matter what account), but the item he/she is looking for does not exist.

If a gene id not exist (like ENSG00000119685sdsd below), it returns code 404 as status, with a message that "Gene not found" in `data`:
![image](https://user-images.githubusercontent.com/2176883/91910176-6ddabf00-eca6-11ea-9153-987c36be5473.png)

However, if a HPO and variant not exist, **it returns 200 (which is success code), and a bundle of wired thing in `data`**.
![image](https://user-images.githubusercontent.com/2176883/91910100-4f74c380-eca6-11ea-84fa-401566642a9f.png)

---

By the way, the message format is better to be the same. Below is a 401 error for a gene, the key for error message is `error`, but in the first figure above, the key is `message`. It took me quite a long time to figure out...
![image](https://user-images.githubusercontent.com/2176883/91910563-29035800-eca7-11ea-9cf4-75f89df1334d.png)

**Comment by alanwilter** [comment] 2021-05-21 12:38
@YuanTian1991, how do you do get the `inspect` debug to show the errors the way you screenshot? I'm using Chrome and Safari and, looking at `Network` tab but I can't figure out how you do.

BTW, right now `variant` returns 400 and `hpo` returns 500.

Could you review this issue and update us with what you'd like to see?

**Comment by YuanTian1991** [comment] 2021-05-21 15:09
Hi @alanwilter 

The frontend relies on redux to fetch data from API. So you can modify the code in redux/action to get the result printed in the console. For example here:

https://github.com/phenopolis/phenopolis_browser/blob/3278be74f668be98d1de6edfa9e71ab311905204/frontend/src/redux/actions/hpo.js#L9

and here:

https://github.com/phenopolis/phenopolis_browser/blob/3278be74f668be98d1de6edfa9e71ab311905204/frontend/src/redux/actions/variant.js#L9

After this line, add `console.log(res)`. Then you should be able to see the returned data from Chrome devtool console.

**Comment by alanwilter** [comment] 2021-05-21 17:31
Thanks @YuanTian1991, I did the changes above and when searching for an existing item, I can see the `data` object in the console, but when I try e.g. `ENSG00000119685sdsd` I got nothing, so I can't reproduce what you see.

So, I'd ask you to tell us if is still there an issue, and if yes, what is it. I use `Inspect`, tab `Network` and when testing with a wrong query I can see 404 for gene and patient.

For variant I have two situations: 400 (bad request) when I sent a malformed query (e.g. localhost:8888/variant/14-76156575), however it does not go back to dashboard., and 404 when I query for a non-existent variant (localhost:8888/variant/14-76156575-A-C), which seems to work as expected.

But when I try a fake hpo I got 500. So I'm asking to try this yourself and tell us what we still need to do, otherwise I'd close this ticket. Should all of then return 404?

**Comment by alanwilter** [comment] 2021-05-21 18:01
BTW @YuanTian1991 I think this is [wrong](https://github.com/phenopolis/phenopolis_browser/blob/b21edb00d8b57a012fb592af8b0aed3d9f17dca2/frontend/src/redux/actions/variant.js#L15) in `variant.js`, line:
```
            payload: { code: 404, message: 'HPO not exist.' },
```
it should be `Variant not exist`.

I also noticed that `variant.js` and `hpo.js` follow a similar structure, while `gene.js` and `individual.js` follow another different structure.

I did a simple test by changing `hpo.py` to return 404 and now when I enter a fake hpo query, the webpage does redirect to `dashboard`.

**Closed** 2021-05-22 05:57 UTC
Labels: Python API

**Comment by YuanTian1991** [comment] 2021-05-22 05:59
Hi @alanwilter I have checked now it seems working well. The key thing I changed is to use status 400 as "404" missing item for variant.

However, I don't know why we can't use same standard to all 4 items? Like for gene/patient, we use 404 to indicate missing item, but for HPO we use 500, for variant we use 400?

**Comment by alanwilter** [comment] 2021-05-24 20:19
Improved with #346
